core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('',HomeView.as_view(),name="homepage"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('ordersummary/', OrderSummaryView.as_view(), name="order-summary"),
    path('Category/<slug>/',CategoryView.as_view(),name="category"),
    path('products/<slug>/',ItemDetailView.as_view(),name="product"),
    path('add-to-cart/<slug>/',AddToCartView.as_view(),name="add-to-cart"),
    path('request-refund/', RequestFundView.as_view(), name="request-refund"),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/',remove_from_cart,name="remove-from-cart"),
    path('remove-item-from-cart/<slug>/',remove_single_item_from_cart,name="remove-single-item-from-cart"),
    path('payment/<payment_option>',PaymentView.as_view(),name="payment"),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('core.urls'),name="core")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse



LABEL_CHOICE = (
    ('p','primary'),
    ('s','secondary'),
    ('d','danger'),
)
ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

STATE_CHOICES = (
    ('BR', 'BIHAR'),
    ('WB', 'WEST BENGAL'),
)
CITY_CHOICES = (
    ('PUR', 'PURNEA'),
)


class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse("core:category",kwargs={
            'slug':self.slug
        })

    def __str__(self):
        return self.title

class Brand(models.Model):
    brand_name = models.CharField(max_length=200)
    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })

    def __str__(self):
        return self.brand_name

class Item(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.SET_NULL,null=True,blank=True)
    label = models.CharField(choices=LABEL_CHOICE,max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    price = models.FloatField()
    discount_price = models.FloatField(null=True, blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product",kwargs={
            'slug':self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_increase_to_cart_url(self):
        return reverse("core:increase_the_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class Variation(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)  # size

    class Meta:
        unique_together = (
            ('item', 'name')
        )

    def __str__(self):
        return self.name

class ItemVariation(models.Model):
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    value = models.CharField(max_length=50)  # S, M, L
    attachment = models.ImageField(blank=True)

    class Meta:
        unique_together = (
            ('variation', 'value')
        )

    def __str__(self):
        return self.value

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)
    item_variations = models.ManyToManyField(ItemVariation)

    def __str__(self):
        return f"{self.qty} of {self.item.title}"

    def get_total_price(self):
        return self.qty * self.item.price

    def get_total_discount_price(self):
        return self.qty * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()

    def total_discount_percentage_price(self):
        return int(100-(self.item.discount_price/self.item.price)*100)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=200)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    address = models.ForeignKey('Address',related_name="shipping_address",on_delete=models.SET_NULL,blank=True,null=True)
    payment = models.ForeignKey('Payment',on_delete=models.SET_NULL,blank=True,null=True)
    ordered = models.BooleanField(default=False)
    coupon = models.ForeignKey('Coupon',on_delete=models.SET_NULL,blank=True,null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    contact = models.IntegerField()
    pincode = models.IntegerField()
    locality = models.CharField(max_length=400)
    street_address = models.TextField(max_length=200)
    city = models.CharField(max_length=200,choices=CITY_CHOICES)
    state = models.CharField(max_length=200,choices=STATE_CHOICES)
    landmarks = models.CharField(max_length=200,blank=True,null=True)
    alternative_no = models.IntegerField(blank=True,null=True)
    address_type = models.CharField(max_length=1,choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    txn_id = models.CharField(max_length=400)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,blank=True,null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=20)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    reason= models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    def __str__(self):
        return f"{self.pk}"

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% load cart_template_tags %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
     <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    .card-img-design{
   width: 100%!important;
   height: 220px!important;
   object-fit: contain;
}
    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body class="grey lighten-5">
     <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
        <a class="navbar-brand waves-effect" href="{% url 'core:homepage' %}">
        <strong class="blue-text">Dj Shop</strong>
        </a>

<ul class="navbar-nav nav-flex-icons mr-auto">
    <li class="nav-item"><a href="" class="nav-link"></a></li>
  </ul>
     <form class="form-inline">
         <div class="input-group my-0">
  <input type="text" class="form-control" type="text" placeholder="Search" aria-label="Search" size="60">
  <div class="input-group-append">
    <button class="btn btn-md btn-default m-0 px-3 py-2 z-depth-0 waves-effect" type="button" id="button-addon2"><i class="fas fa-search"></i></button>
  </div>
</div>
        </form>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">

       <ul class="navbar-nav nav-flex-icons ml-auto">
            {% if request.user.is_authenticated %}

          <li class="nav-item border border-light rounded mr-3">
            <a class="nav-link waves-effect" href="{% url 'core:order-summary' %}">
              <span class="badge red z-depth-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

                <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle waves-effect mr-4 text-capitalize" data-toggle="dropdown"
  aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>

<div class="dropdown-menu">
  <a class="dropdown-item py-1" href="#">My Profile</a>
  <a class="dropdown-item py-1" href="#">My Order</a>
  <a class="dropdown-item py-1" href="#">Setting</a>
  <div class="dropdown-divider"></div>
   <a class="dropdown-item py-1 my-0" href="{% url 'account_logout' %}"><span class="clearfix d-none d-sm-inline-block"> Logout </span></a>
</div>
            </li>

            {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
            {% endif %}
        </ul>

      </div>

    </div>
  </nav>

   <div class="pt-5"> {% if messages %}
          {% for message in messages %}
               <div class="alert mt-5 alert-{{ message.tags }} alert-dismissible fade show">
                    {{ message }}

               <button type="button" class="close" data-dismiss="alert">
                   <span>&times;</span>
               </button>
               </div>
            {% endfor %}
    {% endif %}
   </div>

 {% block content  %}{% endblock content %}
{% block extra_body %}{% endblock %}



    {% include "footer.html" %}
    {% include "scripts.html" %}


 {% block extra_scripts %}{% endblock extra_scripts %}

</body>

</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>




      <div class="row">
        <div class="col-md-8 mb-4">
         {% if address %}
               <h6 class="d-block mt-3">Saved Address</h6>
            <div class="row mb-4">
                {% for foo in address %}
        <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
               <div class="custom-control custom-radio pmd-radio">
                <input type="radio" class="custom-control-input" id="radioclientcustomControlValidation1" value="{{ foo.id }}" name="save_address" required>
                <label class="custom-control-label" for="radioclientcustomControlValidation1">
                    <h6>{{ foo.name }}</h6>
                    <p class="small m-0">{{ foo.contact }} <br>
                    {{ foo.street_address }}, {{ foo.locality }}, {{ foo.get_city_display }} ({{ foo.get_state_display }})
                    </p>
                    <p class="small m-0 font-weight-bold text-capitalize">{{ foo.landmarks }}</p>
                </label>
                <div class="invalid-feedback">Example invalid feedback text</div>
            </div>

            </div>
        </div>
        </div>
                {% endfor %}

            </div>

         {% endif %}
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>


                      <div class="row">
                          <div class="col-lg-6">
                                    {{ form.name|as_crispy_field }}
                                        {{ form.name.errors }}
                          </div>
                          <div class="col-lg-6">
                              {{ form.contact|as_crispy_field }}
                              {{ form.contact.errors }}
                          </div>
                          <div class="col-lg-6">
                              {{ form.pincode|as_crispy_field }}
                              {{ form.pincode.errors }}
                          </div>
                          <div class="col-lg-6">
                              {{ form.locality|as_crispy_field }}
                              {{ form.locality.errors }}
                          </div>
                          <div class="col-lg-12">
                              {{ form.street_address|as_crispy_field }}
                              {{ form.street_address.errors }}
                          </div>

                          <div class="col-lg-6">
                              {{ form.city|as_crispy_field }}
                              {{ form.city.errors }}
                          </div>
                          <div class="col-lg-6">
                              {{ form.state|as_crispy_field }}
                              {{ form.state.errors }}
                          </div>

                          <div class="col-lg-6">
                              {{ form.landmarks|as_crispy_field }}
                              {{ form.landmarks.errors }}
                          </div>
                          <div class="col-lg-6">
                              {{ form.alternative_no|as_crispy_field }}
                              {{ form.alternative_no.errors }}
                          </div>
                      </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>



      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

templates/footer.html
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">



    <hr class="my-4">

    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> Shopping </a>
    </div>
  </footer>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="container">
    <div class="row">
       <div class="col-lg-12">
                   <section class="text-center mb-4 mt-5">
        <div class="row wow fadeIn">
            {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

              <div class="card shadow-sm">
              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top card-img-design" alt="{{ item.title }}-image">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h6>{{ item.item.get_category_display }}</h6>
                </a>
                <h6>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text text-capitalize text-truncate">{{ item.title }}</a>
                </h6>

                <h4 class="h6">
                     {% if item.discount_price %}
                      <span class="mr-1 small grey-text">
                        ₹<del>{{ item.price }}</del>
                      </span>
                      <span class=" font-weight-bold blue-text">₹{{ item.discount_price }}</span>
                  {% else %}
                      <span class=" font-weight-bold blue-text">₹{{ item.price }}</span>
                  {% endif %}
                </h4>

              </div>
            </div>
          </div>
            {% endfor %}


        </div>
     </section>

    {% if is_paginated %}

      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}

          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
            {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number  }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>


        {% if page_obj.has_next %}

          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>

        {% endif %}
        </ul>
      </nav>
    {% endif %}

        </div>
    </div>

    </div>
  </main>


{% endblock %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}

    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0 text-capitalize">{{ order_item.qty }} x {{ order_item.item.title}}</h6>
        </div>
        <span class="text-muted">₹{{ order_item.get_final_price }}</span>
    </li>

    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-₹{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (INR)</span>
        <strong>₹{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="container mt-5">


     <h2>My Carts</h2>

 <div class="row">
     <div class="col-lg-8">
             {% for order_item in object.items.all %}
         <div class="media d-block d-md-flex mt-4">
                <img class="d-block mb-3 mx-auto media-image shadow-sm" width="140px" src="{{ order_item.item.image.url }}"   alt="{{ order_item.item.title }}">
              <div class="media-body text-center text-md-left ml-md-3 ml-0">
                <h5 class="mt-0 font-weight-bold">{{ order_item.item.title }}</h5>
                  <span class="d-block">
                      {% if order_item.item_variations.exists %}
                         {% for foo in order_item.item_variations.all %}
                              <small class="text-muted">{{ foo.variation.name }}: {{ foo.value }}</small>
                          {% endfor %}
                      {% endif %}
                  </span>
              <span class="d-inline-block my-2">
                  {% if order_item.item.discount_price %}
                           <p class="text-dark h5 font-weight-bold d-inline">₹{{ order_item.get_total_discount_price }}</p>
                       <del class="text-muted small mx-1">₹{{ order_item.get_total_price }}</del>
                      <span class="text-success font-weight-bold small mx-1">Saving ₹{{ order_item.get_amount_saved }} ({{ order_item.total_discount_percentage_price }}%)</span>
                    {% else %}
                        <p class="text-dark font-weight-bold">₹{{ order_item.get_total_price }}</p>
                    {% endif %}

                  </span>




              </div>

         </div>

                  <div class="d-inline-block ml-4 float-left">
                  <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}" class=" badge badge-light p-2">
                             <i class="fas fa-minus"></i>
                        </a>
                        <span class="p-2">{{ order_item.qty }}</span>
                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}" class="badge badge-light p-2">
                        <i class="fas fa-plus"></i>
                        </a>
                  </div>
                 <div class="d-inline-block float-right">
                   <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="btn btn-danger btn-sm mt-n3"><i class="fas fa-trash"></i> Remove</a>
                 </div>
                 <div class="clearfix"></div>
                 <hr>

  {% empty %}
            Your cart is empty
            <a href="{% url 'core:homepage' %}" class="btn btn-primary float-right ">Continue Shopping</a>


      {% endfor %}


      {% if object.coupon %}
        <tr>
        <th colspan="4">Coupon</th>
        <th>{{ object.coupon.amount }}</th>
    </tr>
    {% endif %}
 </div>
    <div class="col-lg-4">

            <div class="card shadow-sm sticky-top" style="top:60px!important;">
                <div class="card-header">Price Details</div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
{% if object.get_total %}
        <li class="list-group-item list-group-item-action">Items () <span class="float-right">₹{{ object.get_total }}</span></li>
        <li class="list-group-item list-group-item-action">Delivery Charge <span class="float-right">₹0</span></li>
        <li class="list-group-item list-group-item-action">Order Total  <span class="float-right">₹{{ object.get_total }}</span></li>

            <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Proceed to Checkout</a>
            <a href="{% url 'core:homepage' %}" class="btn btn-primary float-right ">Continue Shopping</a>
        </td>
    </tr>

    {% endif %}
</ul>
                </div>
            </div>


    </div>
</div>
     </div>
  </main>


{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load cart_template_tags %}
{% block content %}

  <main class="mt-4 pt-0">
    <div class="container dark-grey-text">

      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">
          <img src="{{ object.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-md-6 mb-4">
            <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>
            <h2 class="text-capitalize">{{ object.title }} </h2>
            <small class="small text-muted mb-2 text-capitalize">{{ object.brand }}</small>
              <p class="lead">
                      {% if object.discount_price %}
                      <span class="mr-1">
                        <del>₹{{ object.price }}</del>
                      </span>
                      <span>₹{{ object.discount_price }}</span>
                  {% else %}
                      <span>₹{{ object.price }}</span>
                  {% endif %}
            </p>






            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% if request.user|Item_Is_Exit:request.resolver_match.kwargs.slug %}
                <a href="{% url 'core:order-summary' %}" class="btn btn-success btn-md my-0 p">View cart
                    <i class="fas fa-arrow-circle-right ml-1"></i>
                  </a>
                  <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart
                    <i class="fas fa-shopping-cart ml-1"></i>
                  </a>
                {% else %}

                <form action="{{ object.get_add_to_cart_url }}" method="get">
                {% csrf_token %}
               <div class="mb-4">
                {% for foo in object.variation_set.all %}
                <p class=" mb-0 lead font-weight-bold">{{ foo.name }}</p>
                {% for val in foo.itemvariation_set.all  %}
                    <div class="custom-control custom-radio custom-control-inline">
                      <input type="radio" class="custom-control-input" value="{{ val.value }}" id="{{ foo.name }}{{ val.value }}" name="{{ foo.name }}" required>
                      <label class="custom-control-label" for="{{ foo.name }}{{ val.value }}">{{ val.value }}</label>
                    </div>
                    {% endfor %}
                 {% endfor %}
               </div>
                    <button type="submit" class="btn btn-primary btn-md my-0 p">Add to Cart</button>
                  </form>

            {% endif %}
</div>

        </div>
      </div>
      <hr>

      <div class="row d-flex justify-content-center wow fadeIn">

        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
        </div>
      </div>
 </div>

  <div class="container-fluid">
       <div class="row">
         <div class="col-lg-12 "> <h4 class="my-4 h4 text-center">Related Products</h4></div>
    </div>

      <div class="row wow fadeIn">

            {% for item in item %}
          <div class="col-lg-2 col-md-6 mb-4">

              <div class="card shadow-sm">
              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top card-img-design" alt="{{ item.title }}-image">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h6 class="text-truncate">
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text ">{{ item.title }}</a>
                </h6>

                    <h4 class="h6">
                     {% if item.discount_price %}
                      <span class="mr-1 small grey-text">
                        ₹<del>{{ item.price }}</del>
                      </span>
                      <span class=" font-weight-bold blue-text">₹{{ item.discount_price }}</span>
                  {% else %}
                      <span class=" font-weight-bold blue-text">₹{{ item.price }}</span>
                  {% endif %}
                </h4>


              </div>
            </div>
          </div>
            {% endfor %}


        </div>

  </div>

  </main>

{% endblock %}